# Generated by Django 3.1.4 on 2021-02-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='desc',
            new_name='description',
        ),
    ]
