# Generated by Django 3.1.4 on 2021-02-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travello', '0002_auto_20210220_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='mame',
            new_name='name',
        ),
        migrations.AddField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
